name: Print Hello File

on:
  push:
    branches:
      - main

jobs:
  print-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Print hello.txt content
        run: cat hello.txt
